project_id = "hzcnvfqbbzkqyvolokvt"

[functions.seed-employee-test-data]
verify_jwt = false

[functions.get-invitation-by-token]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.generate-shifts]
verify_jwt = false

[functions.publish-shifts]
verify_jwt = false

[functions.cron-generate-shifts]
verify_jwt = false

[functions.archive-shifts]
verify_jwt = false

[functions.generate-optimized-schedule]
verify_jwt = false
